### ISSUE TITLE
Little Light Suros Regime Bug

### ISSUE THREAD

**Issue by RealFake666** [LittleLightForDestiny/littlelight#125]
Suros has a magazine of 36, but the Little Light app shows a magazine of 27 on Suros

**Comment by TheBrenny** [comment]
Are you sure you haven't got any mods on that make it so? Potentially a holster mod or something which refills the magazine beyond capacity? Little Light gets the weapon specs directly from the Destiny Manifest Database, so it's accurate. Even [light.gg records a magazine of 27](https://www.light.gg/db/items/2856683562/suros-regime/).

**Comment by RealFake666** [comment]
No, I'm just saying that Suros has a magazine of 27 in the app, but in the game it has a magazine of 36


And the holster mod only reloads the weapon over time when I'm not holding it in my hand

So a holster mod has nothing to do with the magazine size

**Comment by TheBrenny** [comment]
I'm not sure. I wouldn't say this this bug is with Little Light though, it's probably that the Destiny Manifest Database hasn't been updated by Bungie? Maybe it's getting a mag size change with the upcoming patch?

All I know is that Little Light probably is telling the truth according to the Destiny API.

**Comment by case** [comment]
FWIW, both DIM and the official Destiny companion app from Bungie show 27. So this looks like a bug on Bungie’s side.

**Comment by joaopmarquesini** [comment]
Closing as it is a Bungie API / database issue
