### ISSUE TITLE
crafatable weapons not showing masterwork border

### ISSUE THREAD

**Issue by joaopmarquesini** [LittleLightForDestiny/littlelight#266]
Craftable weapons aren't being shown as masterworks when they are both masterworks and craftables

**Comment by bill0042** [comment]
The problem is that legendary crafted weapons don't say they are masterworked in the profile. I have a number of them, but none say they are masterworked (e.g., "state": 9 = locked + crafted). Both of my crafted, masterworked exotics show masterwork borders such as my Osteo Striga.
![image](https://github.com/LittleLightForDestiny/littlelight/assets/68356139/3e7e4343-b5c2-41b6-b6fb-bfb3a1c36956)

**Comment by bill0042** [comment]
I'm checking to see if there is another way to tell when a crafted weapon is masterworked. Usually it is when the last 2 perk columns have enhanced perks and maybe also when the masterwork bonus perk is selected. I'm not sure what changes in the profile when the last part happens, but after a crafted weapon is leveled up you can apply a stat bonus to it that shows +10 reload speed, +10 handling, etc.

**Comment by joaopmarquesini** [comment]
nah, if it's a bungie bug we just report it and wait for them to fix it, too little of an issue to make a workaround for it

**Comment by joaopmarquesini** [comment]
https://github.com/Bungie-net/api/issues/1839

Gonna keep it out of the next release for now as it may be an API issue.
If Bungie replies that they don't plan to change it then we try to find a workaround for it.
