### ISSUE TITLE
Issues since Shadowkeep

### ISSUE THREAD

**Issue by Kekehippo** [LittleLightForDestiny/littlelight#46]
I've noticed that collections will no longer show what possible perks any random rolled gun can have.  Was this due to an API change on Bungie's side?  Additionally guns in current possession won't show the additional perks that can be selected.

Also armor isn't showing the associated affinity it's tied too.  Either way still loving the app.

**Comment by marquesinijatinha** [comment]
let's go
1 - random perks on collections: I disabled it because it wasn't working properly, reeadded it yesterday, check for an update on app store.
2 - additional perks on owned items: it's a bungie issue, should be fixed by the end of the month (I will probably need to change some things after that is fixed on the API)
3 - armor affinity: just added that in the latest update.
