### ISSUE TITLE
App is freezing on resume 

### ISSUE THREAD

**Issue by lu4nS** [LittleLightForDestiny/littlelight#75]
With the app opened then when I turn on the screen the app freezes and it can't update data. I'm using a zenfone 4 selfie pro Android 7.1.1. It happens constantly. V 1.7.32

**Comment by marquesinijatinha** [comment]
that's pretty strange as I use a somewhat similar device (zenfone max pro m1)
do you have something I should look after (dev options enabled, some setting on the app that's different than the app default, etc) ?
Also, how does it freeze ? the screen becomes totally unresponsive or it only won't load new data ?
Did this start happening after an update or have been happening since you started using the app ?

**Comment by lu4nS** [comment]
I have dev options enabled but I think that's not the problem because this is happening since some days ago something like a week more or less. Doing some tests here looks like the problem happens when I turn on the screen and touch a tab (like the inventory) before the "updating" text was displayed and then it won't respond anymore and nothing changes.

**Comment by lu4nS** [comment]
Also happens without me touching something on resuming the app it freezes and if a touch the tabs it opened this https://www.bungie.net/en/Profile/BungieMembershipType.TigerXbox/4611686018430226498

**Comment by lu4nS** [comment]
the problems doesn't happen anymore
