### ISSUE TITLE
PC Windows Build

### ISSUE THREAD

**Issue by raigfp** [LittleLightForDestiny/littlelight#85]
You've built an amazing tool, but it's not always very useful to manage gear from your phone.
As I see, you already have a desktop version, but for OSX. Do you have any plans to build it for Windows?

**Comment by TheBrenny** [comment]
I understand that this is over a year late, but there's no PC build just yet because Flutter only recently provided support for Windows, which means that it's only now possible to even think about Windows builds.

The problem now is, there are a whole bunch of Packages which Little Light depends on, and since there was no opportunity for them to write Windows-based implementations, Little Light is at the mercy of these packages. I guess there's no ETA just yet.

**Comment by joaopmarquesini** [comment]
@TheBrenny Yes, SQLite is possible to circunvent as we can use json manifest instead just on windows (on some tests JSON manifest proved to be a bit hard to deal with on mobile devices). But there are also some more pain points, there's no deeplink support on flutter for windows yet, and I need to find a way to distribute (and update) the app.
I thought about doing it via MS app store or steam, but haven't checked too far into yet.
I think we can close this one for now.
